server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    driver-class-name: org.postgresql.Driver
    username: amigoscode
    password: password
  jpa:
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true